config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords",
  omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "freemarkets#index"

  resources :freemarkets do
    member do
      get 'buy', to: 'freemarkets#buy'
      post 'pay', to: 'freemarkets#pay'
    end
  end

  scope :mypage do
    resources :users do
      member do
        get 'profile', to: 'users#profile'
      end
      collection do
        get 'purchased', to: 'users#purchased'
        get 'logout', to: 'users#logout'
        get 'list', to: 'users#list'
        get 'complete', to:'users#complete'
      end
    end
    resources :cards, only: [:show, :new] do
      collection do
        post 'show', to: 'cards#show'
        post 'pay', to: 'cards#pay'
        post 'delete', to: 'cards#delete'
      end
    end
  end

  devise_scope :user do
    get 'sign_in/registrstion'=>'users/registrations#registration'
    get "sign_in/phone" => "users/registrations#phone"
    get "sign_in/address" => "users/registrations#adress"
    get "sign_in/credit" => "users/registrations#credit"
    post "sign_in/complete" => "users/registrations#complete"
  end 

  resources 'categories', only: [:index, :show]
  get 'user/show' => "users#show"

end

app/models/freemarket.rb
class Freemarket < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  has_many :orders
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true

  validates :item_images, presence: true, on: :update

end

app/controllers/freemarkets_controller.rb
class FreemarketsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :buy]

  def index
    @freemarkets = Freemarket.where(status: "1").limit(10).order('created_at DESC')
  end

  def show
    @freemarket = Freemarket.includes(:user).find(params[:id])
    prefecture = Prefecture.all
  end

  def new
    @freemarket = Freemarket.new
    @freemarket.item_images.build
  end

  def create
    @freemarket = Freemarket.new(freemarket_params)
    if @freemarket.item_images.blank?
      @freemarket.errors.add(:image_url, "画像を選択してください")
      @freemarket.item_images.build
      render "new"
      return
    end
    if @freemarket.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @freemarket = Freemarket.find(params[:id])
  end

  def update
    @freemarket = Freemarket.find(params[:id])
      if @freemarket.user_id == current_user.id
        @freemarket.update(freemarket_edit_params)
        redirect_to freemarket_path
      end
  end

  def destroy
    @item = find_freemarket_by_id
    @item.destroy
    redirect_to list_users_path
    flash[:notice] = '削除しました'
  end

  def buy
    @user = User.find_by(id: current_user.id)
    @deliver = DeliverAddress.find_by(user_id: current_user.id)
    @item = find_freemarket_by_id
    @card = find_card_by_id
    if user_signed_in? && current_user.id == @item.user_id
      redirect_to freemarket_path(@item)
    elsif @card.present?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    @deliver = DeliverAddress.find_by(user_id: current_user.id)
    @item = find_freemarket_by_id
    @card = find_card_by_id
    begin
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id,
      currency: 'jpy',
      )
      @item.update(status: 2)
      Order.create(
        user_id: current_user.id,
        freemarket_id: @item.id, 
        deliver_address_id: @deliver.id,
      )
      redirect_to purchased_users_path
      flash[:notice] = '購入が完了しました'
    rescue Payjp::PayjpError => e
      redirect_to buy_freemarket_path(@item)
      flash[:alert] = 'このカードはご利用になれません。ご利用のクレジットカード会社へお問い合わせください。'
    end
  end

  private

  def freemarket_params
    params.require(:freemarket).permit(:item, :description, :price, :condition, :ship_charge, :ship_from, :ship_day, item_images_attributes: [:image_url]).merge(user_id: current_user.id)
  end

  def freemarket_edit_params
    params.require(:freemarket).permit(:item, :description, :price, :condition, :ship_charge, :ship_from, :ship_day, item_images_attributes: [:id, :image_url, :_destroy]).merge(user_id: current_user.id)
  end

  def find_card_by_id
    Card.find_by(user_id: current_user.id)
  end

  def find_freemarket_by_id
    Freemarket.find(params[:id])
  end

end

app/views/freemarkets/buy.html.haml
= content_for(:html_title) { '購入を確定 - Fmarket' }
=render "devise/shared/header_login"
#add_card
.ppc-main
  .ppc-main__upper
    .ppc-main__upper--title
      %h1 購入内容の確認
  .ppc-main__middle
    .ppc-main__middle--box
      = image_tag @item.item_images[0].image_url.url, size:'80x80'
      .ppc-main__middle--smallbox
        %p= @item.item
        %span= "¥#{@item.price.to_s(:delimited)}（税込み）"
        %span 送料込み
  .ppc-main__lower
    .ppc-main__lower--box
      .ppc-main__lower--box--small
        .ppc-main__lower--box--small-pay
          .ppc-main__lower--box--small-pay-box
            %h2 支払い金額
            %span= "¥#{@item.price.to_s(:delimited)}"
          %label
            %input{type: "checkbox"}
            ポイントを使用（所持ポイント:P0）
        .ppc-main__lower--box--small-method
          - if @card.blank?
            %h2 支払い方法
            = link_to new_card_path ,class: 'add-link' do
              %i.fas.fa-plus-circle
              %span 登録してください
          - else
            .ppc-main__lower--box--small-method-title
              %h2 支払い方法
              = link_to cards_path ,class: 'add-link' do
                %span 変更する
            .ppc-main__lower--box--small-method-text
              = " クレジットカード "
              %br
              = "************" + @card_info.last4
              - exp_month = @card_info.exp_month.to_s
              - exp_year = @card_info.exp_year.to_s.slice(2,3)
              %br
              = " 有効期限 " + exp_month + " / " + exp_year
              %br
              %figure= render 'cards/logo'
        .ppc-main__lower--box--small-address
          - if @deliver.blank? || @user.last_name.empty? || @user.first_name.empty?
            %h3 配送先
            = link_to "#" ,class: 'add-link' do
              %i.fas.fa-plus-circle
              %span 登録してください
          - else
            .ppc-main__lower--box--small-address-title
              %h3 配送先
              = link_to "#" ,class: 'add-link' do
                %span 変更する
            .ppc-main__lower--box--small-address-text
              %p= "〒" + @deliver.postal_code
              %p="#{@deliver.city}#{@deliver.street_address}#{@deliver.building_name}"
              %p="#{@user.last_name} #{@user.first_name}"
        .ppc-main__lower--box--small-button
          - if @card.blank? || @deliver.blank? || @user.last_name.empty? || @user.first_name.empty?
            = submit_tag '購入する', id: 'no_submit'
          - else
            = form_tag(pay_freemarket_path, method: :post, id: 'charge-form', name: 'inputForm', class: 'pay_card-form') do
              = submit_tag '購入する', id: 'pay_submit', class: 'pay_card-btn'
=render "devise/shared/footer_login"

app/views/freemarkets/edit.html.haml
.wrapper
  %header
    =render "devise/shared/header_login"
  %main.sell-contents
    %section.sell-contents__main
      .sell-content
        .sell-content__inner
          %h2 商品の情報を入力
          .sell-content__form
            = form_for @freemarket do |f|
              .sell-upload
                %label 出品画像
                %span.must 必須
                %p.info 最大10枚までアップロードできます
                .sell-upload__image
                  .item-preview
                    -@freemarket.item_images.each do |image|
                      .item-preview__inner
                        .item-image
                          = image_tag image.image_url.url, width: "112", height: "112", alt: "preview"
                        .item-edit
                          .item-edit__image
                            %label.edit_btn 編集
                          .item-edit__delete
                            %span 削除
                  #image-drop
                    %label{for: "freemarket_item_images_attributes_#{@freemarket.item_images.length}_image_url", class: "label-box", id: "label-box--#{@freemarket.item_images.length}"}
                      .label-content
                        %pre.label-box__text-visible クリックしてファイルをアップロード
                  .hidden-image
                    = f.fields_for :item_images do |i|
                      = i.file_field :image_url, class: "hidden-field"
                      = i.check_box:_destroy, class: "hidden-checkbox"
                    - @freemarket.item_images.length.upto(4) do |i|
                      %input{name: "freemarket[item_images_attributes][#{i}][image_url]", id: "freemarket_item_images_attributes_#{i}_image_url", class:"hidden-field", type:"file"}
              .sell.name
                .form-name
                  %label 商品名
                  %span.must 必須
                  .form-name__input
                    = f.text_field :item, placeholder: '商品名(必須　４０文字まで)', class: 'input-name',  required: ""
                .form-info
                  %label 商品の説明
                  %span.must 必須
                  .form-info__text
                  = f.text_area :description, class:"text-info", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）", required: ""
              .sell.detail
                %h3.detail-category 商品詳細
                .sell-form
                  .form-pulldown
                    %label カテゴリ
                    %span.must 必須
                    .category-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      %select.pulldown
                  .form-pulldown
                    %label 商品の状態
                    %span.must 必須
                    .condition-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      = f.select :condition, ["新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"], {prompt: '---'}, {class: "pulldown", required: ""}
              .sell.shipping
                %h3.shipping-about 配送について
                .sell-form
                  .form-pulldown
                    %label 配送料の負担
                    %span.must 必須
                    .shipping-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      = f.select :ship_charge, ["送料込み（出品者負担）", "着払い（購入者負担）"], {prompt: '---'}, {class: "pulldown",  required: ""}
                  .form-pulldown
                    %label 発送元の地域
                    %span.must 必須
                    .shipping-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      = f.collection_select(:ship_from, Prefecture.all,:name, :name, {prompt: '---'}, {class: 'pulldown'})
                  .form-pulldown
                    %label 発送までの日数
                    %span.must 必須
                    .shipping-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      = f.select :ship_day, ["1〜2日で発送", "2〜3日で発送", "4〜7日で発送"], {prompt: '---'}, {class: "pulldown",  required: ""}

              .sell.price
                %h3.price-limit 販売価格(300~9,999,999)
                .sell-box
                  .sell-box__input
                    .price-input-box
                      %label.input-box__text
                        価格
                        %span.must 必須
                      .input-box__price
                        ¥
                        = f.text_field :price, placeholder: "例) 300", class: "input-price", id: "jsPrice", required: ""

                  .sell-box__tax
                    %label 販売手数料(10%)
                    .price-tax
                      %input#jsTax.input-tax{readonly:"readonly"}
                  .sell-box__total
                    %label 販売利益
                    .price-total
                      %input#jsTotal.input-total{readonly:"readonly"}

              .sell.submit-btn
                %p.sell-text
                  =link_to "", class:"text-warning" do
                    禁止されている出品
                  、
                  =link_to "", class:"text-warning" do
                    行為
                  を必ずご確認ください。
                %span.sell-text またブランド品でシリアルナンバー等がある場合はご記載ください。
                =link_to "", class:"text-warning" do
                  偽ブランドの販売
                %span.sell-text は犯罪であり処罰される可能性があります。
                %p.sell-text
                  また、出品をもちまして
                  =link_to "", class:"text-warning" do
                    加盟店規約
                  に同意したことになります。
                = f.submit '出品する', class: 'form-btn red-btn'
                =link_to freemarket_path, class:"form-btn gray-btn" do
                  もどる
  %footer
  =render "devise/shared/footer_login"

app/views/freemarkets/index.html.haml
%header
  =render "/shared/header"
.toppage-slider
  %ul.toppage-slider__wrapper
    %li.toppage-slider__contents-first
      .toppage-slider__contents-first-content
        = image_tag 'index1.jpg', class: 'toppage-slider__contents-first--camp-photo', size: '1000x390'
    %li.toppage-slider__contents-second
      .toppage-slider__contents-second-content
        = image_tag 'index2.jpg', class: 'toppage-slider__contents-second-content--device-photo',size: '440x390'
        .toppage-slider__contents-second-content-wrapper
          .toppage-slider__contents-second-content-wrapper--large-text
            スマホで かんたん
            %br
            フリマアプリ
          .toppage-slider__contents-second-content-wrapper--small-text
            フリマはスマホアプリからすぐに出品できる
            %br
            購入時も安心な独自システムのアプリです
          .toppage-slider__contents-second-content-wrapper-logos
            = link_to '' do
              = image_tag 'app-store.svg' ,class: 'toppage-slider__contents-second-content-wrapper--app-logo', size: '170x50'
            .toppage-slider__contents-second-content-wrapper-space
            = link_to '' do
              = image_tag 'google-play.png',class: 'toppage-slider__contents-second-content-wrapper--google-logo',size: '170x50'
.toppage-main
  .toppage-main__category-top
    人気のカテゴリー
    %ul.toppage-main__list
      %li.toppage-main__menu
        .toppage-main__logo
          レディース
        .toppage-main__logo
          メンズ
        .toppage-main__logo
          家電・スマホ・カメラ
        .toppage-main__logo
          おもちゃ・ホビー・グッズ


  .toppage-main__category-bottom
    .toppage-main__category-name
      .toppage-main__text
        レディース新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @freemarkets.each do |freemarket|
            - if user_signed_in? 
              -if freemarket.user_id != current_user.id
                .toppage-main__content
                  = link_to freemarket_path(freemarket) do
                    .toppage-main__image
                      = image_tag freemarket.item_images[0].image_url.url
                      %span
                        = freemarket.price
                    .toppage-main__item-name
                      = freemarket.item
            - else
              .toppage-main__content
                = link_to freemarket_path(freemarket) do
                  .toppage-main__image
                    = image_tag freemarket.item_images[0].image_url.url
                    %span
                      = freemarket.price
                  .toppage-main__item-name
                    = freemarket.item



    .toppage-main__category-name
      .toppage-main__text
        メンズ新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @freemarkets.each do |freemarket|
            - if user_signed_in? 
              -if freemarket.user_id != current_user.id
                .toppage-main__content
                  = link_to freemarket_path(freemarket) do
                    .toppage-main__image
                      = image_tag freemarket.item_images[0].image_url.url
                      %span
                        = freemarket.price
                    .toppage-main__item-name
                      = freemarket.item
            - else
              .toppage-main__content
                = link_to freemarket_path(freemarket) do
                  .toppage-main__image
                    = image_tag freemarket.item_images[0].image_url.url
                    %span
                      = freemarket.price
                  .toppage-main__item-name
                    = freemarket.item

    .toppage-main__category-name
      .toppage-main__text
        家電・スマホ・カメラ新着アイテム
        .toppage-main__item-more

          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @freemarkets.each do |freemarket|
            - if user_signed_in? 
              -if freemarket.user_id != current_user.id
                .toppage-main__content
                  = link_to freemarket_path(freemarket) do
                    .toppage-main__image
                      = image_tag freemarket.item_images[0].image_url.url
                      %span
                        = freemarket.price
                    .toppage-main__item-name
                      = freemarket.item
            - else
              .toppage-main__content
                = link_to freemarket_path(freemarket) do
                  .toppage-main__image
                    = image_tag freemarket.item_images[0].image_url.url
                    %span
                      = freemarket.price
                  .toppage-main__item-name
                    = freemarket.item

    .toppage-main__category-name
      .toppage-main__text
        おもちゃ・ホビー・グッズ新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @freemarkets.each do |freemarket|
            - if user_signed_in?
              -if freemarket.user_id != current_user.id
                .toppage-main__content
                  = link_to freemarket_path(freemarket) do
                    .toppage-main__image
                      = image_tag freemarket.item_images[0].image_url.url
                      %span
                        = freemarket.price
                    .toppage-main__item-name
                      = freemarket.item
            - else
              .toppage-main__content
                = link_to freemarket_path(freemarket) do
                  .toppage-main__image
                    = image_tag freemarket.item_images[0].image_url.url
                    %span
                      = freemarket.price
                  .toppage-main__item-name
                    = freemarket.item

  .toppage-main__category-top
    人気のブランド
    %ul.toppage-main__list
      %li.toppage-main__menu
        .toppage-main__logo
          シャネル
        .toppage-main__logo
          ルイヴィトン
        .toppage-main__logo
          シュプリーム
        .toppage-main__logo
          ナイキ

  .toppage-main__category-bottom
    .toppage-main__category-name
      .toppage-main__text
        シャネル新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @freemarkets.each do |freemarket|
            .toppage-main__content
              .toppage-main__image
                = image_tag freemarket.item_images[0].image_url.url
                %span
                  = freemarket.price
              .toppage-main__item-name
                = freemarket.item

    .toppage-main__category-name
      .toppage-main__text
        ルイヴィトン新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @freemarkets.each do |freemarket|
            .toppage-main__content
              .toppage-main__image
                = image_tag freemarket.item_images[0].image_url.url
                %span
                  = freemarket.price
              .toppage-main__item-name
                = freemarket.item

    .toppage-main__category-name
      .toppage-main__text
        シュプリーム新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @freemarkets.each do |freemarket|
            .toppage-main__content
              .toppage-main__image
                = image_tag freemarket.item_images[0].image_url.url
                %span
                  = freemarket.price
              .toppage-main__item-name
                = freemarket.item

    .toppage-main__category-name
      .toppage-main__text
        ナイキ新着アイテム
        .toppage-main__item-more
          = link_to 'もっと見る >', '#', class: 'toppage-main__more-link'
      .toppage-main__item
        .toppage-main__contents
          - @freemarkets.each do |freemarket|
            .toppage-main__content
              .toppage-main__image
                = image_tag freemarket.item_images[0].image_url.url
                %span
                  = freemarket.price
              .toppage-main__item-name
                = freemarket.item

  =render "/shared/sellbutton"
.footertop
  =render "/shared/footertop"
.footer
  =render "/shared/footer"

app/views/freemarkets/new.html.haml
.wrapper
  %header
    =render "devise/shared/header_login"
  %main.sell-contents
    %section.sell-contents__main
      .sell-content
        .sell-content__inner
          %h2 商品の情報を入力
          .sell-content__form
            = form_for @freemarket do |f|
              .sell-upload
                %label 出品画像
                %span.must 必須
                %p.info 最大10枚までアップロードできます
                .sell-upload__image
                  .item-preview
                  #image-drop
                    %label{for: "freemarket_item_images_attributes_0_image_url", class: "label-box", id: "label-box--0"}
                      %pre.label-box__text-visible クリックしてファイルをアップロード
                  .hidden-image
                    = f.fields_for :item_images do |i|
                      = i.file_field :image_url, class: "hidden-field"
                      %input{class:"hidden-field", type: "file", name: "freemarket[item_images_attributes][1][image_url]", id: "freemarket_item_images_attributes_1_image_url" }
                      %input{class:"hidden-field", type: "file", name: "freemarket[item_images_attributes][2][image_url]", id: "freemarket_item_images_attributes_2_image_url" }
                      %input{class:"hidden-field", type: "file", name: "freemarket[item_images_attributes][3][image_url]", id: "freemarket_item_images_attributes_3_image_url" }
                      %input{class:"hidden-field", type: "file", name: "freemarket[item_images_attributes][4][image_url]", id: "freemarket_item_images_attributes_4_image_url" }
                  .error-messages
                    - if @freemarket.errors[:image_url][0]
                      = @freemarket.errors[:image_url][0]
              .sell.name
                .form-name
                  %label 商品名
                  %span.must 必須
                  .form-name__input
                    = f.text_field :item, placeholder: '商品名(必須　４０文字まで)', class: 'input-name',  required: ""
                .form-info
                  %label 商品の説明
                  %span.must 必須
                  .form-info__text
                  = f.text_area :description, class:"text-info", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）", required: ""
              .sell.detail
                %h3.detail-category 商品詳細
                .sell-form
                  .form-pulldown
                    %label カテゴリ
                    %span.must 必須
                    .category-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      %select.pulldown
                  .form-pulldown
                    %label 商品の状態
                    %span.must 必須
                    .condition-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      = f.select :condition, ["新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"], {prompt: '---'}, {class: "pulldown", required: ""}
              .sell.shipping
                %h3.shipping-about 配送について
                .sell-form
                  .form-pulldown
                    %label 配送料の負担
                    %span.must 必須
                    .shipping-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      = f.select :ship_charge, ["送料込み（出品者負担）", "着払い（購入者負担）"], {prompt: '---'}, {class: "pulldown",  required: ""}
                  .form-pulldown
                    %label 発送元の地域
                    %span.must 必須
                    .shipping-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      = f.collection_select(:ship_from, Prefecture.all,:name, :name, {prompt: '---'}, {class: 'pulldown'})
                  .form-pulldown
                    %label 発送までの日数
                    %span.must 必須
                    .shipping-pulldown
                      %i.fas.fa-chevron-down.down-icon
                      = f.select :ship_day, ["1〜2日で発送", "2〜3日で発送", "4〜7日で発送"], {prompt: '---'}, {class: "pulldown",  required: ""}

              .sell.price
                %h3.price-limit 販売価格(300~9,999,999)
                .sell-box
                  .sell-box__input
                    .price-input-box
                      %label.input-box__text
                        価格
                        %span.must 必須
                      .input-box__price
                        ¥
                        = f.text_field :price, placeholder: "例) 300", class: "input-price", id: "jsPrice", required: ""

                  .sell-box__tax
                    %label 販売手数料(10%)
                    .price-tax
                      %input#jsTax.input-tax{readonly:"readonly"}
                  .sell-box__total
                    %label 販売利益
                    .price-total
                      %input#jsTotal.input-total{readonly:"readonly"}

              .sell.submit-btn
                %p.sell-text
                  =link_to "", class:"text-warning" do
                    禁止されている出品
                  、
                  =link_to "", class:"text-warning" do
                    行為
                  を必ずご確認ください。
                %span.sell-text またブランド品でシリアルナンバー等がある場合はご記載ください。
                =link_to "", class:"text-warning" do
                  偽ブランドの販売
                %span.sell-text は犯罪であり処罰される可能性があります。
                %p.sell-text
                  また、出品をもちまして
                  =link_to "", class:"text-warning" do
                    加盟店規約
                  に同意したことになります。
                = f.submit '出品する', class: 'form-btn red-btn'
                =link_to :back, class:"form-btn gray-btn" do
                  もどる
  %footer
  =render "devise/shared/footer_login"

app/views/freemarkets/show.html.haml
- breadcrumb :items
.content
  =render "shared/header"
  =render 'shared/breadcrumb'
  %section.content-main
    %h1.goods-name
      = @freemarket.item
    %p.goods-info
      この商品は
      = @freemarket.user.nickname
      さんが出品した商品になります
    .goods-main
      .goods-photo
        .goods-photo__main
          = image_tag @freemarket.item_images[0].image_url.url, size:'300x300' 
        .goods-photo__sub
          - @freemarket.item_images.each.with_index do |item_image, index|
            = image_tag item_image.image_url.url ,  size:'60x60',class: "image-sub"
      %table.goods-data
        %tr
          %th 出品者
          %td
            = @freemarket.user.nickname
        %tr
          %th カテゴリー
          %td テストカテゴリ
        %tr
          %th ブランド
          %td テストブランド
        %tr
          %th 商品サイズ
          %td M
        %tr
          %th 商品の状態
          %td
            = @freemarket.condition
        %tr
          %th 配送料の負担
          %td
            = @freemarket.ship_charge
        %tr
          %th 配送の方法
          %td フリマらくらく便
        %tr
          %th 配送元地域
          %td
            =@freemarket.ship_from
        %tr
          %th 発送日の目安
          %td
            = @freemarket.ship_day
    - if user_signed_in? && current_user.id != @freemarket.user_id
      .price-box
        %span.price-box__cash
          ¥
          = @freemarket.price.to_s(:delimited)
        %span.price-box__tax (税込)
        %span.price-box_shipping 送料込み
      =link_to buy_freemarket_path, class:"buy-btn" do
        購入画面に進む
      .goods-detail
        %p.goods-detail_comment
          = @freemarket.description
      .btn-box
        .btn-box__left
          =link_to "#", class:"btn btn-good" do
            %i.fas.fa-heart
            %span いいね
            %span.good-count 1
          =link_to "#", class:"btn btn-report" do
            %i.fas.fa-flag
            %span 不適切な商品の報告
        .btn-box__right
          =link_to "#", class:"btn btn-lock" do
            %i.fas.fa-lock
            %span あんしん・あんぜんへの取り組み
  - if user_signed_in? && current_user.id == @freemarket.user_id
    .edit
      .edit-form
        = link_to edit_freemarket_path do
          %button{class:'form-btn edit-btn'}
            %span 商品編集する
        %p or
        %button{class:'form-btn gray-btn comment-send'}
          %span 出品を一時停止する
        = button_to 'この商品を削除する', freemarket_path(@freemarket.id), { method: :delete, id:'item-delete', class:'form-btn gray-btn', data: { confirm: '本当に削除しますか？'} }
  .message
    .message-box
    .message-form
      %form.message-form__content
        %p 相手のことを考え丁寧なコメントを心がけましょう。　不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea{type:'text', name:'message', class:'form-text'}
        %button{type:'submit', class:'form-btn gray-btn comment-send'}
          %span コメントする

  .another-goods
    .another-goods__back
      =link_to "#" do
        %i.fas.fa-chevron-left
        テスト戻る
    .another-goods__next
      =link_to "#" do
        テスト進む
        %i.fas.fa-chevron-right
  .sns-links
    %ul.sns-links__box
      %li.facebook
        =link_to "#" do
          %i.fab.fa-facebook-square.fa-3x.logo-facebook
      %li.twitter
        =link_to "#" do
          %i.fab.fa-twitter.fa-3x.logo-twitter
      %li.line
        =link_to "#" do
          %i.fab.fa-line.fa-3x.logo-line
      %li.pinterest
        =link_to "#" do
          %i.fab.fa-pinterest.fa-3x.logo-pinterest
  = render partial: 'shared/footertop'
  = render partial: 'shared/footer'