config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords",
  omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "freemarkets#index"

  resources :freemarkets do
    member do
      get 'buy', to: 'freemarkets#buy'
      post 'pay', to: 'freemarkets#pay'
    end
  end

  scope :mypage do
    resources :users do
      member do
        get 'profile', to: 'users#profile'
      end
      collection do
        get 'purchased', to: 'users#purchased'
        get 'logout', to: 'users#logout'
        get 'list', to: 'users#list'
        get 'complete', to:'users#complete'
      end
    end
    resources :cards, only: [:show, :new] do
      collection do
        post 'show', to: 'cards#show'
        post 'pay', to: 'cards#pay'
        post 'delete', to: 'cards#delete'
      end
    end
  end

  devise_scope :user do
    get 'sign_in/registrstion'=>'users/registrations#registration'
    get "sign_in/phone" => "users/registrations#phone"
    get "sign_in/address" => "users/registrations#adress"
    get "sign_in/credit" => "users/registrations#credit"
    post "sign_in/complete" => "users/registrations#complete"
  end 

  resources 'categories', only: [:index, :show]
  get 'user/show' => "users#show"

end

app/models/user.rb
class User < ApplicationRecord
  include ActiveRecord::Reflection
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable,omniauth_providers: [:facebook, :google_oauth2]
  has_many :sns_credentials, dependent: :destroy
  has_many :freemarkets
  has_one :deliver_address ,dependent: :destroy
  accepts_nested_attributes_for :deliver_address, allow_destroy: true
  
  has_many :orders
  has_many :cards


  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      else
        user = User.create(
          nickname: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20],
          )
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      end
    end
    return user
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/

  with_options on: :profile do | profile |
    profile.validates :nickname,
      presence: true,
      length:{ maximum: 20}
    profile.validates :email,
      presence: true,
      format: { with: VALID_EMAIL_REGEX , message: 'のフォーマットが不適切です'}
    profile.validates :password,
      presence:true,
      confirmation: true,
      length:{ minimum: 7, maximum: 128},
      format: { with: VALID_PASSWORD_REGEX , message: 'は英字と数字両方を含むパスワードを設定してください'}
    profile.validates :last_name,
      presence: true,
      length:{ maximum: 35}
    profile.validates :first_name,
      presence: true,
      length:{ maximum: 35}
    profile.validates :last_name_kana,
      presence: true,
      length:{ maximum: 35},
      format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい' }
    profile.validates :first_name_kana,
      presence: true,
      length: { maximum: 35},
      format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい' }
    profile.validate :check_birthday  #生年月日用の独自バリデーション
  end
  
  def check_birthday
   
    if birthday.present?
      if birthday > Date.today
        
        errors.add(:birthday, "を正しく入力してください")
      end
    else
    
      errors.add(:birthday, "を入力してください")
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # callback for facebook
  def facebook
    callback_for(:facebook)
  end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"])
    # snsの情報からuserが登録されているか　or snsから情報を取得できているかを確認
    @user = User.where(nickname: info[:user][:nickname]).or(User.where(email: info[:user][:email])).first || info[:user]

    # persisted?はデータがDBに保存されているかを確認する/配列に対しては使えないから@userを定義するときは気をつける
    if @user.persisted?
      #保存されていればログインしてroot_pathにリダイレクトされる
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      # 登録するアクションに取得した値を渡すために。sessionを利用してuserインスタンスを作成する
      session[:nickname] = info[:user][:nickname]
      session[:email] = info[:user][:email]

      #snsでのユーザ登録ではパスワードを入力させないので準備する。パスワードを作成するDeviseメソッドもある。
      #今回のバリデーションは英数字のみなのでこっちを採用
      session[:password_confirmation] = SecureRandom.alphanumeric(30)

      #SnsCredentialが登録されていないとき
      if SnsCredential.find_by(uid: info[:sns][:uid], provider: info[:sns][:provider]).nil?
        #ユーザ登録と同時にsns_credentialも登録するために
        session[:uid] = info[:sns][:uid]
        session[:provider] = info[:sns][:provider]
      end
      #登録フォームのviewにリダイレクトさせる
      redirect_to step1_signups_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  require "payjp"


  def registration
    @user = User.new
    session[:user] = @user

    
  end
  
  def phone
    params[:user][:birthday] = date_create
    session[:user] = user_params

    @user = User.new(user_params)
    if @user.valid?(:profile)
      
    else
      render :registration
      return
    end
  end  


  def adress

    session[:user][:user_phone]  = user_params[:user_phone]

    @user = User.new
    @user.build_deliver_address
    
    session[:deliver_address] = @user.deliver_address

    
    
  end
    
  def credit

    session[:user]["last_name"]        =   user_params[:last_name]
    session[:user]["first_name"]       =   user_params[:first_name]
    session[:user]["last_name_kana"]   =   user_params[:last_name_kana]
    session[:user]["first_name_kana"]  =   user_params[:first_name_kana]
    session[:user]["user_phone"]       =   user_params[:user_phone]
    session[:deliver_address] = user_params[:deliver_address_attributes]
    

    @user = User.new(session[:user])
    @user.build_deliver_address(session[:deliver_address])
    if @user.valid?(:deliver_address)
      if @user.deliver_address.valid?(:deliver_address)
      else
        render :adress
        return
      end
    elsif @user.deliver_address.valid?(:deliver_address)
      render :adress
      return
    else
      render :adress
      return
    end
  end
  
  
  def complete
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if params[:payjp_token].present?
      @customer = Payjp::Customer.create(
        description: 'Fmarket',
        email: session[:user][:email],
        card: params[:payjp_token],
      )
    
    else
      render :credit
      return
    end
      
    
    @user = User.new(session[:user])
    @user.build_deliver_address(session[:deliver_address])
    @user.cards.build(
      user_id:        @user.id,
      customer_id:    @customer.id,
      card_id:        @customer.default_card,
    )
    

    
    if @user.save
      user = @user
      session.clear
      session[:id] = @user.id
      sign_in User.find(session[:id]) unless user_signed_in?
    else
      redirect_to action: 'registration'
    end
    
  end


  
private

def user_params
  params.require(:user).permit(
    :nickname,
    :email,
    :password,
    :first_name,
    :last_name,
    :first_name_kana,
    :last_name_kana,
    :birthday,
    :user_phone,
    deliver_address_attributes:[
      :postal_code,
      :prefecture_id,
      :city,
      :street_address,
    ]
  )
end


def date_create
  date = params[:birthday]
  if date["birthday(1i)"].empty? && date["birthday(2i)"].empty? && date["birthday(3i)"].empty?
    params[:user][:birthday] = ""
    return
  end

  Date.new date["birthday(1i)"].to_i,date["birthday(2i)"].to_i,date["birthday(3i)"].to_i

end




end

app/controllers/users/sessions_contloller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    super
  end
 
  def create
    super
  end
 
  def destroy
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def new  
    super  
  end
 
  def create
    super
  end
 
  def destroy
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
  end

  def profile
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(profile_params)
      redirect_to profile_user_path(user)
      flash[:notice] = '変更しました'
    else
      render 'profile'
      flash[:alert] = '変更に失敗しました'
    end
  end

  def logout
  end

  def purchased
    @orders = Order.where(user_id: current_user.id).includes(:freemarket).limit(10).order('id DESC')
  end

  def list
    @freemarkets = Freemarket.where(user_id: current_user.id, status: 1).limit(10).order('id DESC')
  end

  def complete
    @freemarkets = Freemarket.where(user_id: current_user.id, status: 2).limit(10).order('id DESC')
  end

  private

  def profile_params
    params.require(:user).permit(:nickname, :profile_content)
  end

end

app/views/users/card.html.haml
= content_for(:html_title) { '支払い方法 - Fmarket' }
= render 'shared/header'
= render 'shared/breadcrumb'
%main.card
  .container
    %article.content
      .title
        %h2 支払い方法
      .list-add
        %section.list-add__card
          %h3.sub-title クレジットカード一覧
          .list-add__card--btn
            = link_to cards_create_path do
              %span クレジットカードを追加する
        .list-add__border
        .list-add__payment-link
          %span=link_to '支払い方法について','#'
    %nav= render 'shared/mypage_side'
%nav= render 'shared/sellbutton'
%aside= render 'shared/footertop'
%footer= render 'shared/footer'

app/views/users/complete.html.haml
= content_for(:html_title) { '出品した商品 - 売却済み - Fmarket' }
.header
  = render "shared/header"
  = render 'shared/breadcrumb'
%main.list-wrapper
  .list-side
    = render 'shared/mypage_side'
  %section.list-contents
    %h2.list-contents__index
      出品した商品
    %ul.list-contents__tabs
      %li
        %h3
          =link_to list_users_path do
            出品中
      %li
        %h3
          =link_to '#' do
            取引中
      %li.active
        %h3
          =link_to complete_users_path do
            売却済み
    .list-contents__inner
      %ul.list-contents__inner-items
        - if @freemarkets.present?
          - @freemarkets.each do |freemarket|
            %li.list-contents__inner-item
              =link_to '#', class:'inner-item' do
                .inner-item__image
                  = image_tag freemarket.item_images[0].image_url.url, size:'55x55'
                .inner-item__namebox
                  .inner-item__name
                    =freemarket.item
                  .inner-item__icon
                    %i.far.fa-heart.icon-like
                    %i.far.fa-comment-alt.icon-comment
                .inner-item__chebron
                  %i.fas.fa-chevron-right
        - else
          %li.list-contents__inner-noitem
            売却済みの商品がありません

app/views/users/identification.html.haml
.mypage-main-container
  =render "shared/header"
  %main.mypage-container.cleafix
    =render "shared/mypage_side"
    .indentification-content
      %section.indentification-content__mypage
        %h2.indentification-content__head-top 本人情報の登録
        = form_with model: @user, local: true, class: 'indentification-content__form' do |f|
          %div
            %p.indentification-content__info
              お客さまの本人情報をご登録ください。
              %br
              登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            %p.indentification-content__link
              = link_to '本人確認書類のアップロードについて', " "
              %i.fas.fa-chevron-right
          .indentification-content__group
            = f.label 'お名前'
            %p
              -# = current_user.name ログインしたユーザーの名前
          .indentification-content__group
            = f.label 'お名前カナ'
            %p
              -# = current_user.name_kana
          .indentification-content__group
            = f.label '生年月日'
            %p
              -# = current_user.birthday
          .indentification-content__group
            = f.label '郵便番号', class: 'indentification-content__postcode'
            %span.indentification-content__arbitrary 任意
            = f.text_field :post_code1, { class: 'indentification-content__default', placeholder: '例）1234567', value: "" }
          .indentification-content__group
            = f.label '都道府県', class: 'indentification-content__prefecture'
            %span.indentification-content__arbitrary 任意
            .indentification-content__select
              %i.fas.fa-chevron-down
              -# = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: '--', selected: current_user.prefecture_id
            .indentification-content__group
              = f.label '市区町村', class: 'indentification-content__postcode'
              %span.indentification-content__arbitrary 任意
              = f.text_field :city, { class: 'indentification-content__default', placeholder: '例）横浜市緑区', value: "" }
            .indentification-content__group
              = f.label '番地', class: 'indentification-content__postcode'
              %span.indentification-content__arbitrary 任意
              = f.text_field :address1, { class: 'indentification-content__default', placeholder: '例）青山1-1-1', value: "" }
            .indentification-content__group
              = f.label '建物名', class: 'indentification-content__postcode'
              %span.indentification-content__arbitrary 任意
              = f.text_field :address2, { class: 'indentification-content__default', placeholder: '例）柳ビル103', value: "" }
              = f.submit '登録する', { class: 'indentification-content__button' }
            %p.indentification-content__link
              = link_to '本人情報の登録について', ''
              %i.fas.fa-chevron-right
      = render 'shared/sellbutton'
  = render partial: 'shared/footertop'
= render partial: 'shared/footer'

app/views/users/index.html.haml
- breadcrumb :users
.header
  = render "shared/header"
  = render 'shared/breadcrumb'
.main
  =render "shared/mypage_side"
  =render "shared/mypage_main"
.nav
  = render 'shared/sellbutton'
.footer-top
  = render 'shared/footertop'
.footer
  = render 'shared/footer'

app/views/users/list.html.haml
- breadcrumb :lists
= content_for(:html_title) { '出品した商品 - 出品中 - Fmarket' }
.header
  = render "shared/header"
  = render 'shared/breadcrumb'
%main.list-wrapper
  .list-side
    = render 'shared/mypage_side'
  %section.list-contents
    %h2.list-contents__index
      出品した商品
    %ul.list-contents__tabs
      %li.active
        %h3
          =link_to list_users_path do
            出品中
      %li
        %h3
          =link_to "" do
            取引中
      %li
        %h3
          =link_to complete_users_path do
            売却済み
    .list-contents__inner
      %ul.list-contents__inner-items
        - if @freemarkets.present?
          - @freemarkets.each do |freemarket|
            %li.list-contents__inner-item
              =link_to freemarket_path(freemarket), class:"inner-item" do
                .inner-item__image
                  = image_tag freemarket.item_images[0].image_url.url, size:'55x55'
                .inner-item__namebox
                  .inner-item__name
                    =freemarket.item
                  .inner-item__icon
                    %i.far.fa-heart.icon-like
                    %i.far.fa-comment-alt.icon-comment
                .inner-item__chebron
                  %i.fas.fa-chevron-right
        - else
          %li.list-contents__inner-noitem
            出品中の商品がありません

app/views/users/logout.html.haml
- breadcrumb :logout
= render 'shared/header'
= render 'shared/breadcrumb'
%section.logout-wrapper
  .profile-logout
    = render 'shared/mypage_side'
  .logout-content-wrpper
    =link_to destroy_user_session_path,method: :delete do
      .logout-container
        %form{action: "", method: "post",class: "logout-content"}
          .button
            .logout-content__btn
              ログアウト


  = render "/shared/sellbutton"
.footertop
= render "/shared/footertop"
.footer
= render "/shared/footer"

app/views/users/profile.html.haml
- breadcrumb :profiles
= content_for(:html_title) { 'プロフィール - Fmarket' }
= render 'shared/header'
= render 'shared/breadcrumb'
%main.profile
  .container
    %article.content
      = form_with model: @user, local: true do |f|
        .title
          %h2 プロフィール
        .self
          .self__icon
          = f.text_field :nickname, class:'self__nickname', placeholder: '例)AYA☆セール中'
        .message-form
          = f.text_area :profile_content, class:'message-form__profile', placeholder: '例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪'
          = f.submit '変更する', id:'submit-btn', class:'message-form__update-btn'
    %nav= render 'shared/mypage_side'
%nav= render 'shared/sellbutton'
%aside= render 'shared/footertop'
%footer= render 'shared/footer'

app/views/users/purchased.html.haml
= content_for(:html_title) { '購入した商品 - 過去の取引一覧 - Fmarket' }
= render 'shared/header'
= render 'shared/breadcrumb'
%main.purchased
  .container
    %article.content
      %h2.title 購入した商品
      .tabs
        %ul.tabs__title
          %li
            %h3
              =link_to '#' do
                取引中
          %li.active
            %h3
              =link_to purchased_users_path do
                過去の取引
      %section.tabs__content
        %ul.tabs__content--lists
          - if @orders.present?
            - @orders.each do |order|
              %li.buy-list
                =link_to '#', class:'buy-list__item' do
                  = image_tag order.freemarket.item_images[0].image_url.url, class:'buy-list__item--img', size:'48x48'
                  .buy-list__item--text
                    %p= "「#{order.freemarket.item}」を購入しました。 取引が完了しました"
                    %span 取引完了
                  .buy-list__item--arrow
          - else
            .not-found--img
            .not-found--text
              %span 購入した商品がありません
    %nav= render 'shared/mypage_side'
%nav= render 'shared/sellbutton'
%aside= render 'shared/footertop'
%footer= render 'shared/footer'

app/views/users/show.html.haml
- breadcrumb :show
.mypage-main-container
  =render "shared/header"
  = render 'shared/breadcrumb'
  %main.indentification
    =render "shared/mypage_side"
    .indentification-content
      %section.indentification-content__mypage
        %h2.indentification-content__head-top 本人情報の登録
        = form_with model: @user, local: true, class: 'indentification-content__form' do |f|
          %div
            %p.indentification-content__info
              お客さまの本人情報をご登録ください。
              %br
              登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            %p.indentification-content__link
              = link_to '本人確認書類のアップロードについて', " "
              %i.fas.fa-chevron-right
          .indentification-content__group
            = f.label 'お名前'
            %p
              = current_user.last_name
              = current_user.first_name
          .indentification-content__group
            = f.label 'お名前カナ'
            %p
              = current_user.last_name_kana
              = current_user.first_name_kana
          .indentification-content__group
            = f.label '生年月日'
            %p
              = current_user.birthday
          .indentification-content__group
            = f.label '郵便番号', class: 'indentification-content__postcode'
            %span.indentification-content__arbitrary 任意
            = f.text_field :post_code1, { class: 'indentification-content__default', placeholder: '例）1234567', value: "" }
          .indentification-content__group
            = f.label '都道府県', class: 'indentification-content__prefecture'
            %span.indentification-content__arbitrary 任意
            .indentification-content__select
              %i.fas.fa-chevron-down.down-icon
              = f.collection_select :ship_from, Prefecture.all, :id, :name, {include_blank: '---'}, {class: 'pulldown'}
            .indentification-content__group
              = f.label '市区町村', class: 'indentification-content__postcode'
              %span.indentification-content__arbitrary 任意
              = f.text_field :city, { class: 'indentification-content__default', placeholder: '例）横浜市緑区', value: "" }
            .indentification-content__group
              = f.label '番地', class: 'indentification-content__postcode'
              %span.indentification-content__arbitrary 任意
              = f.text_field :address1, { class: 'indentification-content__default', placeholder: '例）青山1-1-1', value: "" }
            .indentification-content__group
              = f.label '建物名', class: 'indentification-content__postcode'
              %span.indentification-content__arbitrary 任意
              = f.text_field :address2, { class: 'indentification-content__default', placeholder: '例）柳ビル103', value: "" }
              = f.submit '登録する', { class: 'indentification-content__button' }
            %p.indentification-content__link
              = link_to '本人情報の登録について', ''
              %i.fas.fa-chevron-right
      = render 'shared/sellbutton'
= render partial: 'shared/footertop'
= render partial: 'shared/footer'