config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords",
  omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "freemarkets#index"

  resources :freemarkets do
    member do
      get 'buy', to: 'freemarkets#buy'
      post 'pay', to: 'freemarkets#pay'
    end
  end

  scope :mypage do
    resources :users do
      member do
        get 'profile', to: 'users#profile'
      end
      collection do
        get 'purchased', to: 'users#purchased'
        get 'logout', to: 'users#logout'
        get 'list', to: 'users#list'
        get 'complete', to:'users#complete'
      end
    end
    resources :cards, only: [:show, :new] do
      collection do
        post 'show', to: 'cards#show'
        post 'pay', to: 'cards#pay'
        post 'delete', to: 'cards#delete'
      end
    end
  end

  devise_scope :user do
    get 'sign_in/registrstion'=>'users/registrations#registration'
    get "sign_in/phone" => "users/registrations#phone"
    get "sign_in/address" => "users/registrations#adress"
    get "sign_in/credit" => "users/registrations#credit"
    post "sign_in/complete" => "users/registrations#complete"
  end 

  resources 'categories', only: [:index, :show]
  get 'user/show' => "users#show"

end

app/views/shared/_breadcrumb.html.haml
.breadcrumb
  %nav
    = breadcrumbs separator: "&emsp;&emsp;#{content_tag(:i, '', :class=>'fa fa-angle-right')}&emsp;&emsp;"

app/views/shared/_footer.html.haml
.footer
  .topbox
    .box
      .title
        %h2.atitle フリマについて
      .menubox
        .menu
          %li.list 会社概要（運営会社）
          %li.list 採用情報
          %li.list プレスリリース
          %li.list 公式ブログ
          %li.list フリマロゴ利用ガイドライン
          = link_to('https://twitter.com/mercari_jp', class: "link") do
            %i.fab.fa-twitter
          = link_to('https://www.facebook.com/mercarijp', class: "link") do
            %i.fab.fa-facebook-square
    .box
      .title
        %h2.atitle ヘルプ＆ガイド
      .menubox
        .menu
          %li.list フリマガイド
          %li.list らくらくフリマ便
          %li.list ゆうゆうフリマ便
          %li.list 大型フリマ便
          %li.list 車体取引ガイド
          %li.list フリマあんしん・あんぜん宣言！
          %li.list 偽ブランド品撲滅への取り組み
          %li.list フリマボックス
    .box
      .title
        %h2.atitle プライバシーと利用規約
      .menubox
        .smallbox
          .menu
            %li.list プライバシーポリシー
            %li.list フリマ利用規約
            %li.list
              あんしんスマホサポート制度に関
              %br
              する利用特約
            %li.list コンプライアンスポリシー
        .smallbox
          .menu
            %li.list
              個人データの安全管理に係る基本
              %br
              方針
            %li.list 特定商取引に関する表記
            %li.list 資金決済法に基づく表示
            %li.list 法令順守と犯罪抑止のために
    .box
      .title
        %h2.atitle 国
      .menubox
        .menu
          %li.list 日本
          %li.list United States
  .bottombox
    .logo
      = link_to root_path do
        =image_tag "fmarket_logo_red.svg", size: '180x60', class: 'logo-a'
    .corporatemark
      %li.acorporatemark © 2019 Fmarket

app/views/shared/_footer_login.html.haml
.login-header
  %h.header-center
    =link_to '', class: "login-header--link" do
      = image_tag ("fmarket_logo_red.svg")

app/views/shared/_footertop.html.haml
.footertop
  .picture
    = image_tag 'footertop.jpg', height: '260', width: '100%'
    .contents
      .leftcontent
        .upper
          スマホでかんたんフリマアプリ
        .middle
          今すぐ無料ダウンロード！
        .lower
          .left
            = image_tag 'logo_red.svg', height: '50', width: '50'
          .center
            = link_to('https://apps.apple.com/jp/app/id667861049?l=ja') do
              = image_tag 'Download_on_the_App_Store_Badge_JP_RGB_blk_100317.svg', height: '45', width: '144'
          .right
            = link_to('https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja') do
              = image_tag 'google-play-badge.png', height: '60', width: '144'
      .rightcontent
        = image_tag 'index2.jpg', height: '260', width: '300'

app/views/shared/_header.html.haml
%header.main-header
  .header-inner
    .inner-top
      .inner-top__logo
        = link_to root_path do
          = image_tag "fmarket_logo_red.svg", alt: 'logo', height: '36', width: '134', class: 'header-inner__top__logo'
      %form{action:"/", method:"post", class: "inner-top__form"}
        %input{type:"search", placeholder:"何かお探しですか？",class:"search-form"}
        %button{type:"submit", class:"search-form__icon"}
          %i.icon.fas.fa-search
    .inner-lwr
      .lwr-menu
        .lwr-menu__category
          =link_to categories_path ,class:"menu" do
            %i.fas.fa-list-ul
            %span カテゴリーから探す
          .category-list
            %ul.category-list__parent
              - @parents.each do |parent|
                %li.list-parent
                  =link_to category_path(parent),class:"parent-name" do
                    =parent.category_name
                  %ul.list-parent__child
                    - parent.children.each do |child|
                      %li.list-child
                        =link_to category_path(child),class:"child-name" do
                          =child.category_name
                        %ul.list-child__son
                          - child.children.first(15).each do |grandchild|
                            %li.list-son
                              =link_to category_path(grandchild),class:"son-name"do
                                =grandchild.category_name
        .lwr-menu__brand
          =link_to "",class:"menu" do
            %i.fas.fa-tags
            %span ブランドから探す
      .lwr-user
        - if user_signed_in?
          .lwr-user__like
            =link_to"",class:"login-menu" do
              %i.far.fa-heart
              %span いいね！一覧
          .lwr-user__notice
            =link_to"",class:"login-menu" do
              %i.far.fa-bell
              %span お知らせ
          .lwr-user__todo
            =link_to"",class:"login-menu" do
              %i.fas.fa-check
              %span やることリスト
          .lwr-user__mypage
            =link_to  users_path,class:"login-menu" do
              %i.far.fa-user
              %span マイページ
        - else
          .lwr-user__new
            =link_to new_user_registration_path, class:"user-new" do
              新規会員登録
          .lwr-user__login
            =link_to new_user_session_path, class:"user-login" do
              ログイン

app/views/shared/_mypage_main.html.haml
.user
  .user__icon
    =link_to "/" do
      %figure
        = image_tag 'icon.png'
      %h2.bold
        =current_user.nickname
      .mypage-number
        評価 20 出品数 31
  %section.mypage__content
    %ul.mypage__content--tabs
      %li.active.mypage__content--tab
        %h3
          お知らせ 
      %li.mypage__content--tab
        %h3
          やることリスト
    .tab__content
      %ul
        %li
          =link_to "#",class: 'tab__content__item--link' do
            %figure
              =image_tag  ("logo_red.svg")
            .tab__content__item--body
              %p
                通知はありません
              %i.fa.fa-angle-right
        %li
          =link_to "#",class: 'tab__content__item--link' do
            %figure
              =image_tag  ("logo_red.svg")
            .tab__content__item--body
              %p
                通知はありません
              %i.fa.fa-angle-right      
        %li
          =link_to "#",class: 'tab__content__item--link' do
            %figure
              =image_tag  ("logo_red.svg")
            .tab__content__item--body
              %p
                通知はありません
              %i.fa.fa-angle-right                   
        %li
          =link_to "#",class: 'tab__content__item--link' do
            %figure
              =image_tag  ("logo_red.svg")
            .tab__content__item--body
              %p
                通知はありません

              %i.fa.fa-angle-right

        %li.li-go
          .mypage-go
            =link_to "#" ,class: "mypage-go--list"do
              一覧を見る
    .mypage__buy
      .mypage__buy__head
        購入した商品
      %ul.mypage__buy__tabs
        %li.active.mypage__buy__tabs--list.active
          %p
            取引中
        %li.mypage__buy__tabs--list
          %p
            過去の取引
      .mypage__buy__foot
        %ul
          %li.mypage__buy__foot--not-img
          %li.mypage__buy__foot--not-found
            取引中の商品がありません

app/views/shared/_mypage_side.html.haml
.mypage-side
  .mypage-side--nav
    %ul.mypage-side--nav__list
      %li
        =link_to users_path ,class: "mypage-side--nav__list__item active" do
          マイページ
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          お知らせ
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          やる事リスト
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          いいね！一覧
          %i.fa.fa-angle-right
      %li
        =link_to new_freemarket_path ,class: "mypage-side--nav__list__item" do
          出品する
          %i.fa.fa-angle-right
      %li
        =link_to list_users_path , class: "mypage-side--nav__list__item" do
          出品した商品-出品中
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          出品した商品-取引中
          %i.fa.fa-angle-right
      %li
        =link_to complete_users_path , class: "mypage-side--nav__list__item" do
          出品した商品-売却済み
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          購入した商品-取引中
          %i.fa.fa-angle-right
      %li
        =link_to purchased_users_path, class: "mypage-side--nav__list__item" do
          購入した商品-過去の取引
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          ニュース
          %i.fa.fa-angle-right
      %li
        =link_to "#"  ,class: "mypage-side--nav__list__item" do
          評価一覧
          %i.fa.fa-angle-right
      %li
        =link_to "#",  class: "mypage-side--nav__list__item" do
          ガイド
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          お問い合わせ
          %i.fa.fa-angle-right
    .mypage-side--nav__head
      メルペイ
    %ul.mypage-side--nav__list
      %li
        =link_to "#"  ,class: "mypage-side--nav__list__item" do
          残高・振り込み申請
          %i.fa.fa-angle-right
      %li
        =link_to "#"  ,class: "mypage-side--nav__list__item" do
          ポイント
          %i.fa.fa-angle-right 
    .mypage-side--nav__head
      設定
    %ul.mypage-side--nav__list
      %li
        =link_to profile_user_path(current_user.id) ,class: "mypage-side--nav__list__item" do
          プロフィール
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          発送元・お届け先住所変更
          %i.fa.fa-angle-right
      %li
        =link_to cards_path ,class: "mypage-side--nav__list__item" do
          支払い方法
          %i.fa.fa-angle-right
      %li
        =link_to "#" , class: "mypage-side--nav__list__item" do
          メール/パスワード
          %i.fa.fa-angle-right
      %li
        =link_to user_show_path ,class: "mypage-side--nav__list__item" do
          本人情報
          %i.fa.fa-angle-right
      %li
        =link_to logout_users_path , class: "mypage-side--nav__list__item" do
          ログアウト
          %i.fa.fa-angle-right

app/views/shared/_product_purchase_canfirmation.html.haml
.ppc__head
  .ppc__logo
    = image_tag 'fmarket_logo_red.svg', height: '49', width: '185'
.ppc__main
  .title
    %h1.title_text 商品内容の確認
  .product
  .address
  .payment
.foot
  .footmenu
  .footlogo
  .corporatemark

app/views/shared/_sellbutton.html.haml
.toppage-button
  .toppage-button__main
    = link_to new_freemarket_path, class:"toppage-button__main-link", data: {turbolinks: :false} do
      .toppage-button__main-up
        %p
        出品
      .toppage-button__main-bottom
        %i.fas.fa-camera.fa-4x