config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords",
  omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "freemarkets#index"

  resources :freemarkets do
    member do
      get 'buy', to: 'freemarkets#buy'
      post 'pay', to: 'freemarkets#pay'
    end
  end

  scope :mypage do
    resources :users do
      member do
        get 'profile', to: 'users#profile'
      end
      collection do
        get 'purchased', to: 'users#purchased'
        get 'logout', to: 'users#logout'
        get 'list', to: 'users#list'
        get 'complete', to:'users#complete'
      end
    end
    resources :cards, only: [:show, :new] do
      collection do
        post 'show', to: 'cards#show'
        post 'pay', to: 'cards#pay'
        post 'delete', to: 'cards#delete'
      end
    end
  end

  devise_scope :user do
    get 'sign_in/registrstion'=>'users/registrations#registration'
    get "sign_in/phone" => "users/registrations#phone"
    get "sign_in/address" => "users/registrations#adress"
    get "sign_in/credit" => "users/registrations#credit"
    post "sign_in/complete" => "users/registrations#complete"
  end 

  resources 'categories', only: [:index, :show]
  get 'user/show' => "users#show"

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_card

  require "payjp"

  def show
    if @card.present?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(@card.card_id)
    end
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: 'show' if card.present?
  end

  def pay
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    if params['payjp_token'].blank?
      redirect_to action: 'new'
    else
      customer = Payjp::Customer.create(
      description: 'Fmarket',
      email: current_user.email,
      card: params['payjp_token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: 'show'
        flash[:notice] = 'クレジットカードの登録が完了しました'
      else
        redirect_to action: 'pay'
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end

  def delete
    if @card.present?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: 'show'
      flash[:notice] = 'クレジットカードの削除が完了しました'
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/views/cards/_list.html.haml
.list__card--logobtn
  .logo
    = render 'logo'
  .btn
    = form_tag(delete_cards_path, method: :post, id: 'charge-form') do
      = text_field_tag 'card_id', '', type: 'hidden'
      = submit_tag '削除する', id: 'token_delete', class: 'delete-btn'
.list__card--number
  = "************" + @card_info.last4
.list__card--date
  - exp_month = @card_info.exp_month.to_s
  - exp_year = @card_info.exp_year.to_s.slice(2,3)
  = exp_month + " / " + exp_year

app/views/cards/_logo.html.haml
- brand_logo = @card_info.brand
- if brand_logo == 'Visa'
  = image_tag 'visa_logo.svg', alt: 'VISA', size:'60x30'
- elsif brand_logo == 'MasterCard'
  = image_tag 'mc_logo.svg', alt: 'Mastercard', size:'45x35'
- elsif brand_logo == 'JCB'
  = image_tag 'jcb_logo.svg', alt: 'JCB', size:'45x35'
- elsif brand_logo == 'American Express'
  = image_tag 'ae_logo.svg', alt: 'AMERICAN EXPRESS', size:'35x35'
- elsif brand_logo == 'Diners Club'
  = image_tag 'dc_logo.png', alt: 'Diners Club', size:'45x35'
- elsif brand_logo == 'Discover'
  = image_tag 'dis_logo.png', alt: 'DISCOVER', size:'45x35'

app/views/cards/new.html.haml
- breadcrumb :newcard
= content_for(:html_title) { 'クレジットカード情報入力 - Fmarket' }
= render 'shared/header'
= render 'shared/breadcrumb'
%main.card
  .container
    %article.content
      .title
        %h2 クレジットカード情報入力
      .list-add
        .list-add__card
          = form_tag(pay_cards_path, method: :post, id: 'charge-form', name: 'inputForm', class: 'list-add__card__form') do
            %span.payment-errors
            .list-add__card--inum
              %label.sub-title カード番号
              %span.form-req 必須
              %br
              = text_field_tag 'number', '', class: 'list-add__card--inum-no', placeholder: '半角数字のみ' ,maxlength: '16', type: 'text'
              %span.required-num
            .list-add__card--inum-icon
              %figure
                = image_tag 'visa_logo.svg', alt: 'VISA', size:'49x20'
                = image_tag 'mc_logo.svg', alt: 'Mastercard', size:'30x20'
                = image_tag 'sc_logo.svg', alt: 'SAISON CARD', size:'30x20'
                = image_tag 'jcb_logo.svg', alt: 'JCB', size:'30x20'
                = image_tag 'ae_logo.svg', alt: 'AMERICAN EXPRESS', size:'21x20'
                = image_tag 'dc_logo.png', alt: 'Diners Club', size:'32x20'
                = image_tag 'dis_logo.png', alt: 'DISCOVER', size:'32x20'
            .list-add__card--sed
              %label.sub-title 有効期限
              %span.form-req 必須
              %br
              %select{id: 'exp_month', name: 'exp_month', class: 'list-add__card--sed-limit', type: 'text'}
                = ('01'..'12').each do |month|
                  %option{value: month}
                    = month
              %i.icon-arrow-btm
              %span.p-limit 月
              %select{id: 'exp_year', name: 'exp_year', class: 'list-add__card--sed-limit', type: 'text'}
                = (20..30).each do |year|
                  - four_year = '20' + year.to_s
                  %option{value: four_year}
                    = year
              %i.icon-arrow-btm
              %span.p-limit 年
            .list-add__card--iscd
              %label.sub-title セキュリティコード
              %span.form-req 必須
              %br
              = text_field_tag 'cvc', '', class: 'list-add__card--iscd-code', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: '4', type: 'text'
              %span.required-cvc
              .list-add__card--iscd-q
                #click-balloon
                  %span.form-q ?
                  カード裏面の番号とは？
                .balloon
                  %span
                    カードの裏面をご参照ください。
                  %br
                  = image_tag 'c-card_bk.png', alt: '', width: '180'
            = submit_tag '追加する', id: 'token_submit', class: 'list-add__card--btn'
    %nav= render 'shared/mypage_side'
%nav= render 'shared/sellbutton'
%aside= render 'shared/footertop'
%footer= render 'shared/footer'

app/views/cards/show.html.haml
- breadcrumb :cards
= content_for(:html_title) { '支払い方法 - Fmarket' }
= render 'shared/header'
= render 'shared/breadcrumb'
%main.card
  .container
    %article.content
      .title
        %h2 支払い方法
      .list
        %section.list__card
          %h3.sub-title クレジットカード一覧
          - if @card.blank?
            = link_to new_card_path ,class: 'list__card--btn', data: {turbolinks: :false} do
              %span クレジットカードを追加する
          - else
            = render 'list'
        .list__border
        .list__payment-link
          %span=link_to '支払い方法について','#'
    %nav= render 'shared/mypage_side'
%nav= render 'shared/sellbutton'
%aside= render 'shared/footertop'
%footer= render 'shared/footer'